#!/bin/bash
while true; do
  if [[ ! -f /etc/letsencrypt/dhparam.pem ]]; then
    openssl dhparam -dsaparam 4096 -out /etc/letsencrypt/dhparam.pem;
  fi;

  certbot certonly -n --agree-tos --email dacut+zdzops@kanga.org --expand \
  --authenticator certbot-route53:auth \
  --domains 0div0.com,www.0div0.com,backend.0div0.com,zerodivzero.com,www.zerodivzero.com,backend.zerodivzero.com
  certbot certonly -n --agree-tos --email dacut+zdzops@kanga.org --expand \
  --authenticator certbot-route53:auth \
  --domains localdev.zerodivzero.com,localdev.0div0.com
  aws s3 cp /etc/letsencrypt/live/localdev.0div0.com/cert.pem \
    s3://0div0-config/letsencrypt/localdev.0div0.com/cert.pem
  aws s3 cp /etc/letsencrypt/live/localdev.0div0.com/chain.pem \
    s3://0div0-config/letsencrypt/localdev.0div0.com/chain.pem
  aws s3 cp /etc/letsencrypt/live/localdev.0div0.com/fullchain.pem \
    s3://0div0-config/letsencrypt/localdev.0div0.com/fullchain.pem
  aws s3 cp /etc/letsencrypt/live/localdev.0div0.com/privkey.pem \
    s3://0div0-config/letsencrypt/localdev.0div0.com/privkey.pem
  aws s3 cp /etc/letsencrypt/live/localdev.zerodivzero.com/cert.pem \
    s3://0div0-config/letsencrypt/localdev.zerodivzero.com/cert.pem
  aws s3 cp /etc/letsencrypt/live/localdev.zerodivzero.com/chain.pem \
    s3://0div0-config/letsencrypt/localdev.zerodivzero.com/chain.pem
  aws s3 cp /etc/letsencrypt/live/localdev.zerodivzero.com/fullchain.pem \
    s3://0div0-config/letsencrypt/localdev.zerodivzero.com/fullchain.pem
  aws s3 cp /etc/letsencrypt/live/localdev.zerodivzero.com/privkey.pem \
    s3://0div0-config/letsencrypt/localdev.zerodivzero.com/privkey.pem
  sleep 86400 # 1 day
done;
